# Generated by Django 4.2.27 on 2026-03-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_evento_evento_cancelado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservabutaca',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservabutaca',
            name='estado',
            field=models.CharField(choices=[('temporal', 'Temporal'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='temporal', max_length=20),
        ),
        migrations.AddField(
            model_name='reservabutaca',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
