# Generated by Django 4.2.27 on 2026-03-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_reservabutaca_lugar_entrada_reservabutaca_prezo_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('zonas_interes', models.TextField(blank=True, help_text='Lugares dos eventos nos que comprou entradas (separados por comas)', null=True, verbose_name='Zonas de interese')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Data de alta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Suscripción Newsletter',
                'verbose_name_plural': 'Suscripcións Newsletter',
                'ordering': ['-fecha_alta'],
            },
        ),
    ]
