# Generated by Django 4.2.27 on 2026-03-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_suscripcionnewsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='localidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_gestion_entrada',
            field=models.CharField(blank=True, choices=[('pagina', 'a través da páxina'), ('manual', 'a través do organizador'), ('gratis', 'de balde')], max_length=20, null=True),
        ),
    ]
