# Generated by Django 4.2.27 on 2026-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0021_evento_localidade_alter_evento_tipo_gestion_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='coordenadas',
            field=models.JSONField(blank=True, help_text='[lat, lon] ou {lat, lon}', null=True),
        ),
    ]
