# Generated by Django 4.2.27 on 2026-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_evento_coordenadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nota_lugar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
