# Generated by Django 4.2.27 on 2026-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_alter_evento_nota_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='gastos_xestion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaxe de gastos de xestión aplicado ao evento (ex: 5.00 para 5%)', max_digits=5, null=True),
        ),
    ]
