# Generated by Django 4.2.27 on 2026-03-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_evento_total_a_pagar_ao_organizador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='total_a_pagar_ao_organizador',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='total_dinheiro_recadado',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='total_gastos_xestion',
        ),
    ]
