# Generated by Django 4.2.27 on 2026-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0028_remove_evento_total_a_pagar_ao_organizador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='total_a_pagar_ao_organizador',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total a transferir ao organizador tras descontar gastos de xestión', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='total_dinheiro_recadado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de diñeiro recadado polas vendas deste evento', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='total_gastos_xestion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total absoluto de gastos de xestión deste evento', max_digits=12, null=True),
        ),
    ]
