# Generated by Django 4.2.27 on 2026-04-14 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0029_evento_total_a_pagar_ao_organizador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaPrezo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('prezo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='eventos.evento')),
            ],
        ),
    ]
