# Generated by Django 4.2.27 on 2026-04-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0030_zonaprezo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='duracion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
