# Generated by Django 4.2.27 on 2026-04-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0031_evento_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
