# Generated by Django 4.2.27 on 2026-04-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_evento_evento_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='prezo_areas',
            field=models.BooleanField(default=False),
        ),
    ]
