# Generated by Django 4.2.27 on 2026-05-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0035_alter_zonaprezo_prezo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='contrato_ip',
            field=models.CharField(blank=True, help_text='IP dende onde se asinou o contrato.', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='contrato_navegador',
            field=models.CharField(blank=True, help_text='Navegador do usuario ao asinar o contrato.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='contrato_pdf',
            field=models.FileField(blank=True, help_text='Arquivo PDF do contrato asinado.', null=True, upload_to='contratos/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='contrato_timestamp',
            field=models.DateTimeField(blank=True, help_text='Data e hora de sinatura do contrato.', null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='contrato_uid',
            field=models.CharField(blank=True, help_text='Identificador único da sinatura do contrato.', max_length=32, null=True, unique=True),
        ),
    ]
