# Generated by Django 4.2.27 on 2026-05-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0036_evento_contrato_ip_evento_contrato_navegador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento_cobrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_envio_email_agradecemento_cobro',
            field=models.BooleanField(default=False),
        ),
    ]
