# Generated by Django 4.2.27 on 2026-05-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0037_evento_evento_cobrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservabutaca',
            name='entrada_usada_validacion',
            field=models.BooleanField(default=False),
        ),
    ]
