# Generated by Django 4.2.27 on 2026-05-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0038_reservabutaca_entrada_usada_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
