# Generated by Django 4.2.27 on 2026-05-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0039_evento_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='slug',
        ),
    ]
