# Generated by Django 4.2.27 on 2026-06-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0040_remove_evento_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='numero_iban',
        ),
    ]
