# Generated by Django 4.2.27 on 2026-06-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0041_remove_evento_numero_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservabutaca',
            name='codigo_factura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
