# Generated by Django 4.2.27 on 2026-06-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0042_reservabutaca_codigo_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservabutaca',
            name='codigo_factura',
        ),
        migrations.AddField(
            model_name='evento',
            name='codigo_factura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
