# Generated by Django 4.2.29 on 2026-06-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0043_remove_reservabutaca_codigo_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='total_gastos_xestion_iva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total absoluto de gastos de xestión deste evento con IVE', max_digits=12, null=True),
        ),
    ]
