# Generated by Django 4.2.29 on 2026-06-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0044_evento_total_gastos_xestion_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='factura_pdf',
            field=models.FileField(blank=True, help_text='Arquivo PDF da factura.', null=True, upload_to='facturas/'),
        ),
    ]
