# Generated by Django 4.2.29 on 2026-06-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0046_reservabutaca_prezo_pvp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='prezo_evento',
            new_name='prezo_recibe_organizador',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='prezo_pvp',
            new_name='prezo_venta',
        ),
    ]
