# Generated by Django 4.2.27 on 2026-06-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0047_rename_prezo_evento_evento_prezo_recibe_organizador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zonaprezo',
            old_name='prezo',
            new_name='prezo_recibe_organizador',
        ),
        migrations.RenameField(
            model_name='zonaprezo',
            old_name='prezo_pvp',
            new_name='prezo_venta',
        ),
    ]
