# Generated by Django 4.2.27 on 2026-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0048_rename_prezo_zonaprezo_prezo_recibe_organizador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='asume_gastos_organizador',
            field=models.BooleanField(default=False),
        ),
    ]
