# Generated by Django 4.2.27 on 2026-07-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0049_evento_asume_gastos_organizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='duracion',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_evento_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_evento_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
