# Generated by Django 4.2.27 on 2026-05-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0009_organizador_idioma_organizador_numero_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='enderezo_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizador',
            name='nif_cif',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizador',
            name='nome_razon_social_contrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
