# Generated by Django 4.2.27 on 2026-05-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0010_organizador_enderezo_fiscal_organizador_nif_cif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizador',
            name='nome_razon_social_contrato',
        ),
    ]
