# Generated by Django 4.2.27 on 2026-05-26 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0011_remove_organizador_nome_razon_social_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{5,20}$', message='Teléfono inválido')]),
        ),
    ]
