# Generated by Django 4.2.27 on 2026-06-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0012_alter_organizador_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='data_nacemento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizador',
            name='tipo_organizador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
