# Generated by Django 4.2.27 on 2026-06-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0013_organizador_data_nacemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
