# Generated by Django 4.2.27 on 2026-06-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0014_organizador_nome_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='apelidos_organizador',
            field=models.CharField(default='apelido', max_length=255),
        ),
    ]
