# Generated by Django 4.2.27 on 2026-06-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0015_organizador_apelidos_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='web_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
