# Generated by Django 4.2 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizador", "0016_organizador_web_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizador",
            name="stripe_connect_account_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="organizador",
            name="stripe_onboarding_completado",
            field=models.BooleanField(default=False),
        ),
    ]
